apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: server
        envFrom:
        - secretRef:
            name: server-secret
        - configMapRef:
            name: server-config
        # TODO secret config setting
        # - configMapRef:
        #   name: server-config
        # env:
        # - name: SERVER_DB_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: server-secret
        #       key: db-password
        volumeMounts:
        - name: volume-secret
          readOnly: true
          mountPath: /etc/secret
        imagePullPolicy: Always
        ports:
          - containerPort: 50051
      - name: mysql
        image: mysql
        envFrom:
        - configMapRef:
            name: mysql-config
        volumeMounts:
        - name: volume-mysql
          readOnly: true
          mountPath: /docker-entrypoint-initdb.d
        imagePullPolicy: Always
        ports:
          - containerPort: 3306
      volumes:
      - name: volume-secret
        secret:
          secretName: server-secret
          items:
          - key: firebase-admin-sdk.json
            path: firebase-admin-sdk.json
      - name: volume-mysql
        configMap:
          name: mysql-config
          items:
          - key: init.sql
            path: init.sql
