namespace: dev

bases:
- ../../bases

patchesStrategicMerge:
- client/service-patch.yaml

secretGenerator:
- name: server-secret
  # TODO secret setting
  # literals:
  # DB_PASSWARD
  # SENDGRID
  files:
  - secret/envoy.yaml
  - secret/firebase-admin-sdk.json

configMapGenerator:
- name: server-config
  env: server/config.env
  behavior: merge

images:
- name: client
  newName: gcr.io/two_choices_dev/client_user
  newTag: "latest"
- name: server
  newName: gcr.io/two_choices_dev/server
  newTag: "latest"
