FROM node:16.3.0 as builder

WORKDIR /app
COPY ./two_choices_client /app

RUN cd /app/ && \
    npm install && \
    npm run build && \
    npm run generate

FROM nginx:1.21

COPY ./docker/two_choices_client/nginx/nginx.conf /etc/nginx/nginx.conf
COPY ./docker/two_choices_client/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf

COPY --from=builder /app/dist /app/dist
